<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDekab1d\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDekab1d/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDekab1d.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDekab1d\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDekab1d\appDevDebugProjectContainer([
    'container.build_hash' => 'Dekab1d',
    'container.build_id' => 'f60a2672',
    'container.build_time' => 1701634679,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDekab1d');
